Form
Mehria-Rahmani/mobile-project.github.io pull request #3
Opened 2022-06-07 13:34 UTC by Mehria-Rahmani

-create a contact form for my project.

2022-06-07 14:07 UTC, danmainah requested changes
Hi @Mehria-Rahmani , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a contribution from one person yet is a group project, kindly make sure everybody contributes to the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-06-07 15:46 UTC, jaflih reviewed
Hi @Mehria-Rahmani , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that is pair programming, so both students should contribute.

Kindly make sure everybody in your team contributes to the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-06-08 09:02 UTC, elyor-doniyorov requested changes
Hi @Mehria-Rahmani, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✔️ There are no linter errors
✔️ All input field have required attribute
✔️ etc.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- to add a good `description`, a `screenshot`, `how to setup` section, `issue page link` in your Readme file.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 09:02 UTC, elyor-doniyorov commented on index.html
> +            <form>
- [ ] Kindly use in your form tag the `action `and `method `attribute to integrate with [formspree service](https://formspree.io/html) 👇 
* `action` value should be similar to `https://formspree.io/f/{form_id}`
* `method` value equals `POST`;

2022-06-08 09:02 UTC, elyor-doniyorov commented on index.html
> +            <li><textarea name="message" id="message" placeholder="Enter text here"></textarea></li>
- [ ] Also please make sure that `name `input has `maxlength="30"` attribute and `message `input has `maxlength="500"` attribute.

2022-06-08 09:44 UTC, danmainah requested changes
Hi  @Team, 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 09:44 UTC, danmainah commented on index.html
> +            <li><textarea name="message" id="message" minlength="500" placeholder="Enter text here"></textarea></li>
- [ ] @Team good job so far, kindly check your attribute `minlength` , it supposes to be `maxlength`.Also, make sure your form submits data to your `Formspree` account.

2022-06-08 10:38 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @Team


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 
✅ Nice design 🔥 
✅ Linters are passing 👏 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 10:39 UTC, Mehria-Rahmani commented
Thank you so much

On Wed, Jun 8, 2022, 3:08 PM zieeco ***@***.***> wrote:

> ***@***.**** approved this pull request.
> status: APPROVED 🟢 💯
>
> Hi, @Team
>
> [image:
> 68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966]
> <https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif>
>
> Good job so far 👍 Your project is complete! There is nothing else to say
> other than... it's time to merge it [image: :shipit:]
> Congratulations! 🎉
> Highlights ⚡
>
> ✅ Nice design 🔥
> ✅ Linters are passing 👏
> Optional suggestions
>
>    - N/A
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Mehria-Rahmani/mobile-project/pull/3#pullrequestreview-999505393>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYG63GFXL6EI4DAGQ2ELH73VOBZ2RANCNFSM5YC64MTQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-09 13:20 UTC, merged